version: "3.4"

services:

  urlshortener-service:
    build: 
      context: .
      dockerfile: src/Services/Go/src/urlshortener.api/Dockerfile
    depends_on: 
      - datastore

  datastore:
    image: mongo